first_clip:
  file: img_3753.mov
  text: "Trust me, you\u2019ll thank yourself later\u2014take a moment right now to\
    \ back up your important files!"
  duration: 6.74
  start_time: 0.0
  text_color: white
  scale: 1.0
  voice: alloy
middle_clips:
- file: img_3780.mov
  text: I just discovered the most amazing hotel, and you seriously need to add it
    to your travel list!
  duration: 5.45
  start_time: 0.0
  text_color: white
  scale: 1.0
  voice: alloy
- file: img_3782.mov
  text: "I seriously had to make sure this was legit because it\u2019s incredible\u2014\
    you need to experience this yourself!"
  duration: 7.62
  start_time: 0.0
  text_color: white
  scale: 1.0
  voice: alloy
last_clip:
  file: img_3785.mov
  text: "Trust me, you cannot miss the hotel\u2019s nightly magic show\u2014it completely\
    \ blew me away and you\u2019ll love it!"
  duration: 5.0
  start_time: 0.0
  text_color: yellow
  scale: 1.0
  voice: alloy
  
render:
  tts_enabled: true
  tts_voice: alloy
  fg_scale_default: 0.95

  music_enabled: true
  music_file: luxury-modern-hotel-aesthetic.mp3
  music_volume: 0.25

cta:
  enabled: true
  text: Book now and save 15%
  position: bottom